import { v4 as uuidv4} from 'uuid';

/*
export const Groups = [
    {
        "id" : uuidv4(),
        "group_name" : "Alfa",
        "members" : "John Anna KB" ,
        "members_spec" : "frontend design backend",
        "description" : "We like people",        
        "subjects" : "AK2 PEA",
    },
    {
        "id" : uuidv4(),
        "group_name" : "Beta",
        "members" : "Karen Charles" ,
        "members_spec" : "nothing",
        "description" : "We are funny",        
        "subjects" : "AK2 PEA",
    },
    {
        "id" : uuidv4(),
        "group_name" : "Delta",
        "members" : "Trevor Kate" ,
        "members_spec" : "sports",
        "description" : "We dont like people",        
        "subjects" : "AK2 PEA",
    },]
*/
export const Groups = [{"id":1,"group_name":"Pelecanus conspicillatus","members":"Y-find","members_spec":"Magnesium Chloride, Dextrose monohydrate, Lactic Acid, Sodium Chloride, Sodium Bicarbonate, and Potassium Chloride","description":"Rosaceae","subjects":"Quality Engineer"},
{"id":2,"group_name":"Bos taurus","members":"Zamit","members_spec":"Simvastatin","description":"Poaceae","subjects":"Compensation Analyst"},
{"id":3,"group_name":"Toxostoma curvirostre","members":"Tin","members_spec":"DOCUSATE SODIUM","description":"Pertusariaceae","subjects":"VP Quality Control"},
{"id":4,"group_name":"Crotalus adamanteus","members":"Fixflex","members_spec":"MAGNESIUM ASCORBYL PHOSPHATE","description":"Fagaceae","subjects":"VP Quality Control"},
{"id":5,"group_name":"Lycosa godeffroyi","members":"Biodex","members_spec":"Anti-Fungal Liquid Maximum Strength","description":"Parmeliaceae","subjects":"Senior Financial Analyst"},
{"id":6,"group_name":"Tenrec ecaudatus","members":"Temp","members_spec":"Titanium Dioxide","description":"Brunelliaceae","subjects":"Quality Control Specialist"},
{"id":7,"group_name":"Diomedea irrorata","members":"Zontrax","members_spec":"bupropion hydrochloride","description":"Meliaceae","subjects":"Sales Associate"},
{"id":8,"group_name":"Naja haje","members":"Bigtax","members_spec":"Acetaminophen","description":"Ranunculaceae","subjects":"Assistant Manager"},
{"id":9,"group_name":"Varanus komodensis","members":"Flexidy","members_spec":"Tolnaftate","description":"Lecideaceae","subjects":"Safety Technician I"},
{"id":10,"group_name":"Spermophilus parryii","members":"Ronstring","members_spec":"Horse Epithelium","description":"Asteraceae","subjects":"Dental Hygienist"},
{"id":11,"group_name":"Centrocercus urophasianus","members":"Zamit","members_spec":"Parsnip","description":"Malvaceae","subjects":"Junior Executive"},
{"id":12,"group_name":"Irania gutteralis","members":"Duobam","members_spec":"Metformin Hydrochloride","description":"Brassicaceae","subjects":"Chemical Engineer"},
{"id":13,"group_name":"Coendou prehensilis","members":"Zoolab","members_spec":"Ibuprofen","description":"Fabaceae","subjects":"Environmental Specialist"},
{"id":14,"group_name":"Haematopus ater","members":"Ventosanzap","members_spec":"Mirtazapine","description":"Malvaceae","subjects":"Research Assistant III"},
{"id":15,"group_name":"Tringa glareola","members":"Bamity","members_spec":"BUSPIRONE HYDROCHLORIDE","description":"Asteraceae","subjects":"Nurse Practicioner"},
{"id":16,"group_name":"Thylogale stigmatica","members":"Stringtough","members_spec":"midodrine hydrochloride","description":"Aquifoliaceae","subjects":"Help Desk Operator"},
{"id":17,"group_name":"Colobus guerza","members":"Pannier","members_spec":"Loratadine, Pseudoephedrine Sulfate","description":"Arthoniaceae","subjects":"VP Marketing"},
{"id":18,"group_name":"Bassariscus astutus","members":"Flowdesk","members_spec":"Neomycin sulfate, Polymyxin B Sulfate and Bacitracin Zinc","description":"Onagraceae","subjects":"Software Engineer III"},
{"id":19,"group_name":"Tockus flavirostris","members":"Duobam","members_spec":"Chondrus crispus, Glycyrrhiza glabra, Sarsaparilla, Zingiber officinale, Adrenalinum, Allium cepa, Aralia racemosa, Arsenicum album, Calcarea carbonica, Cantharis, Iodium, Natrum carbonicum, Rhus toxi","description":"Brassicaceae","subjects":"Chemical Engineer"},
{"id":20,"group_name":"Phoenicopterus ruber","members":"Treeflex","members_spec":"Ibuprofen","description":"Buxaceae","subjects":"Analyst Programmer"},
{"id":21,"group_name":"Ramphastos tucanus","members":"Overhold","members_spec":"rufinamide","description":"Asteraceae","subjects":"Developer III"},
{"id":22,"group_name":"Phalacrocorax brasilianus","members":"Mat Lam Tam","members_spec":"CARBIDOPA AND LEVODOPA","description":"Amaranthaceae","subjects":"Dental Hygienist"},
{"id":23,"group_name":"Loxodonta africana","members":"Opela","members_spec":"Triclosan","description":"Euphorbiaceae","subjects":"Safety Technician I"},
{"id":24,"group_name":"Lybius torquatus","members":"Flowdesk","members_spec":"Acetaminophen","description":"Parmeliaceae","subjects":"Design Engineer"},
{"id":25,"group_name":"Kobus leche robertsi","members":"Tresom","members_spec":"Benzethonium Chloride","description":"Aizoaceae","subjects":"Speech Pathologist"},
{"id":26,"group_name":"Spheniscus magellanicus","members":"Subin","members_spec":"Metformin Hydrochloride","description":"Salicaceae","subjects":"Analog Circuit Design manager"},
{"id":27,"group_name":"Felis silvestris lybica","members":"Vagram","members_spec":"BUTALBITAL, ACETAMINOPHEN AND CAFFEINE","description":"Clavariaceae","subjects":"Senior Sales Associate"},
{"id":28,"group_name":"Aegypius tracheliotus","members":"Flowdesk","members_spec":"Fluconazole","description":"Verrucariaceae","subjects":"Quality Engineer"},
{"id":29,"group_name":"Cebus nigrivittatus","members":"Cardguard","members_spec":"Naproxen Sodium","description":"Cladoniaceae","subjects":"Food Chemist"},
{"id":30,"group_name":"Vombatus ursinus","members":"Andalax","members_spec":"BUPIVACAINE HYDROCHLORIDE","description":"Polemoniaceae","subjects":"Senior Quality Engineer"},
{"id":31,"group_name":"Acrantophis madagascariensis","members":"Treeflex","members_spec":"Promethazine Hydrochloride","description":"Polygonaceae","subjects":"Occupational Therapist"},
{"id":32,"group_name":"Myotis lucifugus","members":"Zoolab","members_spec":"Benzoyl Peroxide","description":"Polygonaceae","subjects":"Analog Circuit Design manager"},
{"id":33,"group_name":"Larus novaehollandiae","members":"Wrapsafe","members_spec":"Naphazoline hydrochloride, Polysorbate 80","description":"Ranunculaceae","subjects":"Senior Editor"},
{"id":34,"group_name":"Macaca mulatta","members":"Fix San","members_spec":"Lovastatin","description":"Capparaceae","subjects":"Data Coordiator"},
{"id":35,"group_name":"Graspus graspus","members":"Biodex","members_spec":"Aesculus hippocastanum 2X, Potentilla anserina 2X, Cuprum aceticum 6X, Secale cornutum 4X, Tabacum 4X, Veratrum album 6X","description":"Poaceae","subjects":"Chief Design Engineer"},
{"id":36,"group_name":"Trichechus inunguis","members":"Vagram","members_spec":"juniperus virginiana pollen","description":"Hypnaceae","subjects":"Senior Financial Analyst"},
{"id":37,"group_name":"Gabianus pacificus","members":"Hatity","members_spec":"ESTRADIOL","description":"Asteraceae","subjects":"Editor"},
{"id":38,"group_name":"Macropus rufogriseus","members":"Treeflex","members_spec":"Salicylic Acid","description":"Portulacaceae","subjects":"Biostatistician IV"},
{"id":39,"group_name":"Cebus nigrivittatus","members":"Trippledex","members_spec":"Burweed Marsh Elder","description":"Peltigeraceae","subjects":"Operator"},
{"id":40,"group_name":"Mazama gouazoubira","members":"Pannier","members_spec":"OXYGEN","description":"Thymelaeaceae","subjects":"Statistician IV"},
{"id":41,"group_name":"Didelphis virginiana","members":"Cardify","members_spec":"ESZOPICLONE","description":"Cyperaceae","subjects":"Environmental Tech"},
{"id":42,"group_name":"Mellivora capensis","members":"Zontrax","members_spec":"DOK Plus","description":"Scrophulariaceae","subjects":"Food Chemist"},
{"id":43,"group_name":"Calyptorhynchus magnificus","members":"Trippledex","members_spec":"Dextromethorphan Hydrobromide, Doxylamine Succinate","description":"Scrophulariaceae","subjects":"Geologist IV"},
{"id":44,"group_name":"Deroptyus accipitrinus","members":"Alphazap","members_spec":"Sodium Bicarbonate","description":"Euphorbiaceae","subjects":"Geological Engineer"},
{"id":45,"group_name":"Pelecans onocratalus","members":"Cardify","members_spec":"Helianthemum nummularium flower, Clematis Vitalba Top, Impatiens glandulifera flower, Prunus cerasifera flower, and Ornithogalum umbellatum","description":"Asteraceae","subjects":"Biostatistician I"},
{"id":46,"group_name":"Bos taurus","members":"Daltfresh","members_spec":"Donepezil hydrochloride","description":"Porpidiaceae","subjects":"Statistician IV"},
{"id":47,"group_name":"Felis silvestris lybica","members":"Konklab","members_spec":"Arnica Montana","description":"Poaceae","subjects":"Office Assistant II"},
{"id":48,"group_name":"Loris tardigratus","members":"Wrapsafe","members_spec":"Metoprolol Succinate","description":"Scrophulariaceae","subjects":"Senior Quality Engineer"},
{"id":49,"group_name":"Chauna torquata","members":"Keylex","members_spec":"ASPIRIN","description":"Asteraceae","subjects":"Civil Engineer"},
{"id":50,"group_name":"Lutra canadensis","members":"Viva","members_spec":"CHLORAL HYDRATE","description":"Onagraceae","subjects":"Director of Sales"},
{"id":51,"group_name":"Ara macao","members":"Bitwolf","members_spec":"Azithromycin","description":"Polygonaceae","subjects":"Professor"},
{"id":52,"group_name":"Egretta thula","members":"Transcof","members_spec":"loperamide HCl","description":"Nyctaginaceae","subjects":"Marketing Manager"},
{"id":53,"group_name":"unavailable","members":"Matsoft","members_spec":"TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE","description":"Encalyptaceae","subjects":"Geological Engineer"},
{"id":54,"group_name":"Alopex lagopus","members":"Zaam-Dox","members_spec":"ampicillin sodium","description":"Asteraceae","subjects":"Software Test Engineer IV"},
{"id":55,"group_name":"Haematopus ater","members":"Temp","members_spec":"Fluticasone Propionate","description":"Splachnaceae","subjects":"Structural Analysis Engineer"},
{"id":56,"group_name":"Ateles paniscus","members":"Duobam","members_spec":"TITANIUM DIOXIDE","description":"Lamiaceae","subjects":"Clinical Specialist"},
{"id":57,"group_name":"Felis wiedi or Leopardus weidi","members":"Zathin","members_spec":"Triamcinolone Acetonide","description":"Asteraceae","subjects":"Statistician I"},
{"id":58,"group_name":"Bassariscus astutus","members":"Veribet","members_spec":"Acetaminophen","description":"Amaranthaceae","subjects":"Business Systems Development Analyst"},
{"id":59,"group_name":"Otocyon megalotis","members":"Fix San","members_spec":"Ensulizole, Octinoxate, and Titanium dioxide","description":"Amaranthaceae","subjects":"Food Chemist"},
{"id":60,"group_name":"Boa constrictor mexicana","members":"Pannier","members_spec":"DIGOXIN","description":"Parmeliaceae","subjects":"Account Executive"},
{"id":61,"group_name":"Geochelone elegans","members":"Cardguard","members_spec":"Paricalcitol","description":"Cactaceae","subjects":"Engineer III"},
{"id":62,"group_name":"Macropus rufogriseus","members":"Treeflex","members_spec":"Tall Ragweed","description":"Rosaceae","subjects":"Occupational Therapist"},
{"id":63,"group_name":"Phylurus milli","members":"Duobam","members_spec":"One Seed Juniper","description":"Anomodontaceae","subjects":"Analyst Programmer"},
{"id":64,"group_name":"Eudyptula minor","members":"Zontrax","members_spec":"Lisinopril","description":"Verbenaceae","subjects":"Senior Sales Associate"},
{"id":65,"group_name":"Panthera leo","members":"Domainer","members_spec":"Eucalyptol, Menthol, Methyl Salicylate, and Thymol","description":"Asteraceae","subjects":"Cost Accountant"},
{"id":66,"group_name":"Macropus parryi","members":"Kanlam","members_spec":"OCTINOXATE and TITANIUM DIOXIDE","description":"Bryaceae","subjects":"Senior Quality Engineer"},
{"id":67,"group_name":"Gyps fulvus","members":"Temp","members_spec":"Octocrylene","description":"Pannariaceae","subjects":"Help Desk Technician"},
{"id":68,"group_name":"Callipepla gambelii","members":"Bitwolf","members_spec":"famotidine, calcium carbonate and magnesium hydroxide","description":"Onagraceae","subjects":"Account Representative III"},
{"id":69,"group_name":"Vulpes vulpes","members":"Bigtax","members_spec":"Coffea Cruda, Cypripendium, Hyoscyamus and Matricaria Chamomilla","description":"Catillariaceae","subjects":"Accountant IV"},
{"id":70,"group_name":"Taurotagus oryx","members":"Flexidy","members_spec":"Silver Maple","description":"Gentianaceae","subjects":"Help Desk Technician"},
{"id":71,"group_name":"Spermophilus tridecemlineatus","members":"Fix San","members_spec":"Midazolam","description":"Lecanoraceae","subjects":"Director of Sales"},
{"id":72,"group_name":"Alopochen aegyptiacus","members":"Zaam-Dox","members_spec":"White petrolatum","description":"Rubiaceae","subjects":"Marketing Assistant"},
{"id":73,"group_name":"Propithecus verreauxi","members":"Opela","members_spec":"Hydroquinone","description":"Scrophulariaceae","subjects":"Financial Analyst"},
{"id":74,"group_name":"Martes pennanti","members":"Zontrax","members_spec":"Cetirizine HCl","description":"Hydrophyllaceae","subjects":"Occupational Therapist"},
{"id":75,"group_name":"Varanus salvator","members":"Ronstring","members_spec":"Lidocaine Hydrochloride","description":"Phyllachoraceae","subjects":"Registered Nurse"},
{"id":76,"group_name":"Charadrius tricollaris","members":"Zathin","members_spec":"Isopropyl Alcohol","description":"Asteraceae","subjects":"VP Accounting"},
{"id":77,"group_name":"Felis libyca","members":"Cardguard","members_spec":"Phentermine Hydrochloride","description":"Rhamnaceae","subjects":"Food Chemist"},
{"id":78,"group_name":"Felis chaus","members":"Ronstring","members_spec":"Avobenzone, Octisalate, Octocrylene","description":"Araliaceae","subjects":"Geological Engineer"},
{"id":79,"group_name":"Papio ursinus","members":"Tres-Zap","members_spec":"Abrotanum, Aesculus hipp., Allium sativum, Arsenicum alb., Artemisia, Baptisia, Cina, Cuprum met., Filix mas, Granatum, Ipecac, Lachesis, Lycopodium, Merc. viv, Naphthalinum, Nat. mur., Nux vom., Pulsatilla, Ratanhia, Ruta, Sabadilla, Santoninum, Silicea, Spigelia anth., Terebinthina, Teucrium marum, Thymolum, Zingiber, Juglans regia","description":"Nyctaginaceae","subjects":"Mechanical Systems Engineer"},
{"id":80,"group_name":"Macropus rufogriseus","members":"Ventosanzap","members_spec":"phenylephrine hcl, brompheniramine maleate","description":"Liliaceae","subjects":"Tax Accountant"},
{"id":81,"group_name":"Thalasseus maximus","members":"Konklux","members_spec":"Citalopram Hydrobromide","description":"Polygonaceae","subjects":"Administrative Officer"},
{"id":82,"group_name":"Callipepla gambelii","members":"Bamity","members_spec":"ARIPIPRAZOLE","description":"Fabaceae","subjects":"Staff Scientist"},
{"id":83,"group_name":"Isoodon obesulus","members":"Kanlam","members_spec":"simvastatin","description":"Asteraceae","subjects":"Chemical Engineer"},
{"id":84,"group_name":"Sarkidornis melanotos","members":"Y-Solowarm","members_spec":"FOLIC ACID, .BETA.-CAROTENE, ASCORBIC ACID, CHOLECALCIFEROL, .ALPHA.-TOCOPHEROL ACETATE, DL-, THIAMINE MONONITRATE, RIBOFLAVIN, NIACINAMIDE, PYRIDOXINE HYDROCHLORIDE, CYANOCOBALAMIN, CALCIUM PANTOTHENATE, CALCIUM CARBONATE, FERROUS FUMARATE, and ZINC OXIDE","description":"Asteraceae","subjects":"Engineer II"},
{"id":85,"group_name":"Ploceus rubiginosus","members":"Bytecard","members_spec":"Ferric Subsulfate","description":"Asteraceae","subjects":"Electrical Engineer"},
{"id":86,"group_name":"unavailable","members":"Keylex","members_spec":"Anagrelide Hydrochloride","description":"Fabaceae","subjects":"Clinical Specialist"},
{"id":87,"group_name":"Sitta canadensis","members":"Greenlam","members_spec":"Quetiapine fumarate","description":"Menispermaceae","subjects":"Legal Assistant"},
{"id":88,"group_name":"Mirounga leonina","members":"Bytecard","members_spec":"verapamil hydrochloride","description":"Acanthaceae","subjects":"Associate Professor"},
{"id":89,"group_name":"Echimys chrysurus","members":"Sonair","members_spec":"nitrogen","description":"Fabaceae","subjects":"Computer Systems Analyst I"},
{"id":90,"group_name":"Casmerodius albus","members":"Fixflex","members_spec":"cetirizine hydrochloride","description":"Liliaceae","subjects":"Civil Engineer"},
{"id":91,"group_name":"Bradypus tridactylus","members":"Flowdesk","members_spec":"clonazepam","description":"Urticaceae","subjects":"Electrical Engineer"},
{"id":92,"group_name":"Lemur catta","members":"Temp","members_spec":"Benzoyl Peroxide","description":"Asteraceae","subjects":"Senior Sales Associate"},
{"id":93,"group_name":"unavailable","members":"Treeflex","members_spec":"Camphor, Menthol, Methyl Salicylate","description":"Sterculiaceae","subjects":"Quality Engineer"},
{"id":94,"group_name":"Podargus strigoides","members":"Ronstring","members_spec":"Hydralazine Hydrochloride","description":"Magnoliaceae","subjects":"Executive Secretary"},
{"id":95,"group_name":"Pavo cristatus","members":"Flowdesk","members_spec":"Prednisone","description":"Cyatheaceae","subjects":"Civil Engineer"},
{"id":96,"group_name":"Otaria flavescens","members":"Tres-Zap","members_spec":"COLISTIMETHATE SODIUM","description":"Asteraceae","subjects":"Senior Quality Engineer"},
{"id":97,"group_name":"Martes pennanti","members":"Home Ing","members_spec":"acetaminophen","description":"Bryaceae","subjects":"Developer III"},
{"id":98,"group_name":"Sula dactylatra","members":"Zathin","members_spec":"Chlorzoxazone","description":"Piperaceae","subjects":"Data Coordiator"},
{"id":99,"group_name":"Actophilornis africanus","members":"Fix San","members_spec":"Levofloxacin","description":"Limnanthaceae","subjects":"Nurse Practicioner"},
{"id":100,"group_name":"Trachyphonus vaillantii","members":"Sub-Ex","members_spec":"Doxylamine succinate","description":"Anacardiaceae","subjects":"VP Accounting"}]

