import { v4 as uuidv4} from 'uuid';
/*
export const Students = [
{
    "id" : uuidv4(),
    "first_name" : "Alan",
    "surname" : "Green" ,
    "email" : "abc",
    "description" : "I like butter",
    "tags" : "a b",
    "subjects" : "maths physics",
},
{
    "id" : uuidv4(),
    "first_name" : "John",
    "surname" : "Beck" ,
    "email" : "dfv",
    "description" : "I like butter",
    "tags" : "c d",
    "subjects" : "english programming",
},
{
    "id" : uuidv4(),
    "first_name" : "Anna",
    "surname" : "Malt" ,
    "email" : "miu",
    "description" : "I like butter",
    "tags" : "e f",
    "subjects" : "sports german",
}]
*/
export const Students = [{"id":1,"first_name":"Roarke","surname":"Moncarr","email":"rmoncarr0@webeden.co.uk","description":"DIPYRIDAMOLE","tags":"Alpine Fleabane","subjects":"archive"},
{"id":2,"first_name":"Charlie","surname":"Winfrey","email":"cwinfrey1@tripod.com","description":"Fosinopril Sodium","tags":"Mt. Diablo Helianthella","subjects":"Expanded"},
{"id":3,"first_name":"Kalle","surname":"Sutehall","email":"ksutehall2@nytimes.com","description":"Donepezil hydrochloride","tags":"Lipped Orchid","subjects":"well-modulated"},
{"id":4,"first_name":"Michal","surname":"Sainsbury-Brown","email":"msainsburybrown3@so-net.ne.jp","description":"RHODOTORULA RUBRA","tags":"Giant Arrowhead","subjects":"Cross-group"},
{"id":5,"first_name":"Debbie","surname":"Tunnoch","email":"dtunnoch4@istockphoto.com","description":"THERA Moisturizing Body Cleanser","tags":"Nechamandra","subjects":"Business-focused"},
{"id":6,"first_name":"Miner","surname":"Blazej","email":"mblazej5@ibm.com","description":"up and up miconazole 7","tags":"Large Fever Berry","subjects":"secondary"},
{"id":7,"first_name":"Sal","surname":"Durgan","email":"sdurgan6@ocn.ne.jp","description":"Lisinopril","tags":"Christmas Mistletoe","subjects":"Enhanced"},
{"id":8,"first_name":"Page","surname":"Erb","email":"perb7@delicious.com","description":"Exchange Select Calcium Antacid","tags":"Divaricate Navarretia","subjects":"Reactive"},
{"id":9,"first_name":"Nickolas","surname":"Ninnotti","email":"nninnotti8@people.com.cn","description":"Lyrica","tags":"Wig Knapweed","subjects":"Up-sized"},
{"id":10,"first_name":"Trenton","surname":"Morton","email":"tmorton9@hhs.gov","description":"ALETRIS FARINOSA","tags":"Wright's Cliffbrake","subjects":"human-resource"},
{"id":11,"first_name":"Dacey","surname":"Glencross","email":"dglencrossa@twitter.com","description":"PENTOXIFYLLINE","tags":"Tall Yellowtop","subjects":"array"},
{"id":12,"first_name":"Nelson","surname":"Hands","email":"nhandsb@desdev.cn","description":"Sun Defense UVscreen SPF 48","tags":"Wavyleaf Indian Paintbrush","subjects":"incremental"},
{"id":13,"first_name":"Nancee","surname":"Pulley","email":"npulleyc@businessinsider.com","description":"Moisture Therapy","tags":"Custard Orchid","subjects":"protocol"},
{"id":14,"first_name":"Gabbey","surname":"Berthome","email":"gberthomed@imdb.com","description":"Dial Complete Antibacterial Foaming Hand Washkitchen crisp limkitchen crisp lim","tags":"Hawai'i Bog Orchid","subjects":"Synergized"},
{"id":15,"first_name":"Carol-jean","surname":"Lightbourn","email":"clightbourne@ycombinator.com","description":"Oxygen","tags":"Showy Buttercup","subjects":"Cloned"},
{"id":16,"first_name":"Quill","surname":"Pennicott","email":"qpennicottf@chron.com","description":"Nasal","tags":"Mountain Yellowseed","subjects":"optimizing"},
{"id":17,"first_name":"Dev","surname":"Leades","email":"dleadesg@wunderground.com","description":"ESIKA 3-IN-1 PRO MAKE UP FOUNDATION SPF 20 BASE DE MAQUILLAJE PARA ROSTRO 3-EN-1 PRO FPS 20","tags":"Rothrock's Crownbeard","subjects":"Decentralized"},
{"id":18,"first_name":"Haven","surname":"Knappitt","email":"hknappitth@infoseek.co.jp","description":"sunmark ibuprofen","tags":"Carolina Frostweed","subjects":"Profound"},
{"id":19,"first_name":"Cordula","surname":"Minshall","email":"cminshalli@mlb.com","description":"phentermine hydrochloride","tags":"Island Wallflower","subjects":"orchestration"},
{"id":20,"first_name":"Baxter","surname":"Caldera","email":"bcalderaj@scientificamerican.com","description":"Aminosyn","tags":"Bonnet Orchid","subjects":"installation"},
{"id":21,"first_name":"Leese","surname":"Gayton","email":"lgaytonk@istockphoto.com","description":"Neutrogena","tags":"Bright Green Dudleya","subjects":"time-frame"},
{"id":22,"first_name":"Rozella","surname":"Baudouin","email":"rbaudouinl@histats.com","description":"ANTIBACTERIAL HAND SP WITH LIGHT MOISTURIZERS","tags":"Hoary Brome","subjects":"Up-sized"},
{"id":23,"first_name":"Mitch","surname":"Wint","email":"mwintm@blogtalkradio.com","description":"Synalar","tags":"Rough Avens","subjects":"methodology"},
{"id":24,"first_name":"Wilburt","surname":"Dufaur","email":"wdufaurn@yolasite.com","description":"DIABETIC ULCER DEFENSE","tags":"Sedge","subjects":"user-facing"},
{"id":25,"first_name":"Kamila","surname":"Foley","email":"kfoleyo@technorati.com","description":"Up and Up nicotine","tags":"Acinos","subjects":"standardization"},
{"id":26,"first_name":"Nedi","surname":"Rendall","email":"nrendallp@nytimes.com","description":"Erythromycin","tags":"Deviltree","subjects":"Operative"},
{"id":27,"first_name":"Hettie","surname":"Loyns","email":"hloynsq@de.vu","description":"Instant Hand Sanitizer Fresh Lemon Scented","tags":"Norway Sedge","subjects":"value-added"},
{"id":28,"first_name":"Hillery","surname":"MacGeffen","email":"hmacgeffenr@marriott.com","description":"Lorazepam","tags":"Waghorne's Pore Lichen","subjects":"3rd generation"},
{"id":29,"first_name":"Robina","surname":"Landells","email":"rlandellss@wunderground.com","description":"Koh Gen Do Aqua Foundation","tags":"Carey's Balsamroot","subjects":"executive"},
{"id":30,"first_name":"Nikolaus","surname":"Fairbourn","email":"nfairbournt@statcounter.com","description":"Hand Essentials Antibacterial","tags":"Silky Prairie Clover","subjects":"Mandatory"},
{"id":31,"first_name":"Dasha","surname":"Southorn","email":"dsouthornu@goo.gl","description":"Cheongin Haejanghwan","tags":"Gladiolus","subjects":"orchestration"},
{"id":32,"first_name":"Ansel","surname":"Holdforth","email":"aholdforthv@sina.com.cn","description":"ATORVASTATIN CALCIUM","tags":"Palo Blanco","subjects":"solution-oriented"},
{"id":33,"first_name":"Blake","surname":"Ayton","email":"baytonw@mlb.com","description":"Phentermine Hydrochloride","tags":"Piedmont Azalea","subjects":"human-resource"},
{"id":34,"first_name":"Francklin","surname":"Kinmond","email":"fkinmondx@sohu.com","description":"good neighbor pharmacy ibuprofen","tags":"Subalpine Fleabane","subjects":"Diverse"},
{"id":35,"first_name":"Isacco","surname":"Tilmouth","email":"itilmouthy@goo.gl","description":"Lovastatin","tags":"Beachstar","subjects":"Cross-group"},
{"id":36,"first_name":"Murry","surname":"Brymner","email":"mbrymnerz@hc360.com","description":"Timolol Maleate","tags":"Shoshonea","subjects":"Reduced"},
{"id":37,"first_name":"Ardys","surname":"Langmuir","email":"alangmuir10@com.com","description":"Bejinj 40 (Number 8)","tags":"Syrrhopodon Moss","subjects":"analyzing"},
{"id":38,"first_name":"Erek","surname":"Steaning","email":"esteaning11@ovh.net","description":"Clindamycin Hydrochloride","tags":"Beach Wormwood","subjects":"solution-oriented"},
{"id":39,"first_name":"Kevan","surname":"Hemms","email":"khemms12@statcounter.com","description":"PlusPHARMA","tags":"Desert Starvine","subjects":"Seamless"},
{"id":40,"first_name":"Melissa","surname":"McIlreavy","email":"mmcilreavy13@jugem.jp","description":"Folli Pilose","tags":"Hooker's Desert Sandwort","subjects":"User-friendly"},
{"id":41,"first_name":"Arthur","surname":"Bembridge","email":"abembridge14@ifeng.com","description":"Insects (whole body) cockroach mix","tags":"Shortleaf Wild Coffee","subjects":"application"},
{"id":42,"first_name":"Laureen","surname":"McAdam","email":"lmcadam15@soup.io","description":"ZENPEP","tags":"Blumer's Draba","subjects":"Multi-channelled"},
{"id":43,"first_name":"Alejandrina","surname":"Tutchell","email":"atutchell16@economist.com","description":"Minocin","tags":"Anderson's Buttercup","subjects":"portal"},
{"id":44,"first_name":"Romy","surname":"Gosford","email":"rgosford17@spiegel.de","description":"antiperspirant deodorant","tags":"Scutula Lichen","subjects":"adapter"},
{"id":45,"first_name":"Alon","surname":"Cairns","email":"acairns18@yellowbook.com","description":"Demser","tags":"Red Alder","subjects":"Secured"},
{"id":46,"first_name":"Olga","surname":"Guinery","email":"oguinery19@theglobeandmail.com","description":"Doxycycline Hyclate","tags":"Whitney's Bristleweed","subjects":"flexibility"},
{"id":47,"first_name":"Jourdain","surname":"Goman","email":"jgoman1a@etsy.com","description":"Hydroxyzine Hydrochloride","tags":"Whitehead Navarretia","subjects":"multimedia"},
{"id":48,"first_name":"Mendie","surname":"Coode","email":"mcoode1b@engadget.com","description":"Thioridazine Hydrochloride","tags":"Stoneseed","subjects":"3rd generation"},
{"id":49,"first_name":"Ariana","surname":"Surgeoner","email":"asurgeoner1c@e-recht24.de","description":"","tags":"Coastal Bird's-foot Trefoil","subjects":"core"},
{"id":50,"first_name":"Crosby","surname":"Gluyas","email":"cgluyas1d@goo.gl","description":"CYZONE","tags":"Pitcherplant","subjects":"customer loyalty"},
{"id":51,"first_name":"Scarface","surname":"Tingly","email":"stingly1e@printfriendly.com","description":"Anastrozole","tags":"Woolly Fingergrass","subjects":"Re-contextualized"},
{"id":52,"first_name":"Lion","surname":"Oxer","email":"loxer1f@mozilla.com","description":"Treatment Set TS329123","tags":"Sandplain Flax","subjects":"throughput"},
{"id":53,"first_name":"Vanya","surname":"Sturch","email":"vsturch1g@ed.gov","description":"Benicar","tags":"False Goldeneye","subjects":"demand-driven"},
{"id":54,"first_name":"Montgomery","surname":"Jarrard","email":"mjarrard1h@wordpress.org","description":"ASPERGILLUS NIGER VAR NIGER","tags":"Michel's Earth Lichen","subjects":"coherent"},
{"id":55,"first_name":"Aubrey","surname":"Willbraham","email":"awillbraham1i@stanford.edu","description":"SOFT DERM INTENSIVE DEFENSE 8 SPF","tags":"Naupaka","subjects":"fresh-thinking"},
{"id":56,"first_name":"Ronny","surname":"Nore","email":"rnore1j@engadget.com","description":"Ifosfamide and Mesna","tags":"Green Field Speedwell","subjects":"policy"},
{"id":57,"first_name":"Laurianne","surname":"Georgiades","email":"lgeorgiades1k@devhub.com","description":"LBEL FILLING EFFECT FOUNDATION SPF 10","tags":"Gopherweed","subjects":"upward-trending"},
{"id":58,"first_name":"Alice","surname":"Christiensen","email":"achristiensen1l@pen.io","description":"Trimethoprim","tags":"Tinypetal Waxweed","subjects":"Extended"},
{"id":59,"first_name":"Celle","surname":"Parades","email":"cparades1m@nymag.com","description":"Notatum","tags":"Sandpuffs","subjects":"info-mediaries"},
{"id":60,"first_name":"Eirena","surname":"O'Hone","email":"eohone1n@abc.net.au","description":"Rizatriptan Benzoate","tags":"Heated Phacelia","subjects":"Robust"},
{"id":61,"first_name":"Dimitry","surname":"Levett","email":"dlevett1o@usatoday.com","description":"Eucerin","tags":"Oldfield Grass","subjects":"circuit"},
{"id":62,"first_name":"Hart","surname":"Deinhardt","email":"hdeinhardt1p@archive.org","description":"BIVIGAM","tags":"Horseweed","subjects":"Adaptive"},
{"id":63,"first_name":"Nikita","surname":"Pittendreigh","email":"npittendreigh1q@trellian.com","description":"Alendronate Sodium","tags":"Carolina Fimbry","subjects":"even-keeled"},
{"id":64,"first_name":"Nappy","surname":"Seamen","email":"nseamen1r@google.co.uk","description":"Docusate Sodium Stool Softener","tags":"Palmer's Spineflower","subjects":"monitoring"},
{"id":65,"first_name":"Jabez","surname":"Errichi","email":"jerrichi1s@sun.com","description":"Losartan Potassium and Hydrochlorothiazide","tags":"Angel's Trumpets","subjects":"maximized"},
{"id":66,"first_name":"Odella","surname":"Broadfoot","email":"obroadfoot1t@geocities.jp","description":"Phendimetrazine Tartrate","tags":"Fire Reedgrass","subjects":"local area network"},
{"id":67,"first_name":"Justina","surname":"Janczewski","email":"jjanczewski1u@go.com","description":"Common Cold","tags":"Dwarf Ayenia","subjects":"moratorium"},
{"id":68,"first_name":"Danit","surname":"Middleweek","email":"dmiddleweek1v@theatlantic.com","description":"Sure Original Solid Fresh Scent","tags":"Surfgrass","subjects":"monitoring"},
{"id":69,"first_name":"Anastassia","surname":"Capsey","email":"acapsey1w@google.cn","description":"Nifedipine","tags":"Orphniospora Lichen","subjects":"neural-net"},
{"id":70,"first_name":"Alair","surname":"Summons","email":"asummons1x@instagram.com","description":"Amlodipine Besylate","tags":"Kenwood Marsh Checkerbloom","subjects":"Synergistic"},
{"id":71,"first_name":"Garwin","surname":"Junkin","email":"gjunkin1y@nifty.com","description":"Multi-System Support","tags":"New Mexico Phacelia","subjects":"incremental"},
{"id":72,"first_name":"Emmalee","surname":"Beasant","email":"ebeasant1z@freewebs.com","description":"isosorbide mononitrate","tags":"Tetracarpidium","subjects":"analyzer"},
{"id":73,"first_name":"Elwin","surname":"Hatje","email":"ehatje20@etsy.com","description":"Combivent Respimat","tags":"Baja Buckwheat","subjects":"reciprocal"},
{"id":74,"first_name":"Tulley","surname":"Tinan","email":"ttinan21@hud.gov","description":"esika","tags":"Eightpetal Mountain-avens","subjects":"Decentralized"},
{"id":75,"first_name":"Onofredo","surname":"Alelsandrovich","email":"oalelsandrovich22@hp.com","description":"DDF Advanced Moisture Defense","tags":"Psorula Lichen","subjects":"workforce"},
{"id":76,"first_name":"Rozanne","surname":"Renzini","email":"rrenzini23@hp.com","description":"Naproxen","tags":"Baby Jump-up","subjects":"Organized"},
{"id":77,"first_name":"Felic","surname":"Patterson","email":"fpatterson24@tinyurl.com","description":"Tramadol Hydrochloride","tags":"Triangle Cactus","subjects":"Adaptive"},
{"id":78,"first_name":"Dan","surname":"Roistone","email":"droistone25@tinyurl.com","description":"Warfarin Sodium","tags":"Groundcover Milkvetch","subjects":"Mandatory"},
{"id":79,"first_name":"Mellicent","surname":"Priter","email":"mpriter26@walmart.com","description":"Bacitracin","tags":"Fernleaf Licorice-root","subjects":"Devolved"},
{"id":80,"first_name":"Selinda","surname":"Housley","email":"shousley27@cbsnews.com","description":"Metoclopramide","tags":"Bateman's Buckwheat","subjects":"Monitored"},
{"id":81,"first_name":"Risa","surname":"Castleman","email":"rcastleman28@cdbaby.com","description":"Pentoxifylline","tags":"Japanese Privet","subjects":"model"},
{"id":82,"first_name":"Waly","surname":"Raund","email":"wraund29@miibeian.gov.cn","description":"Paroxetine","tags":"Browneyed Susan","subjects":"Multi-tiered"},
{"id":83,"first_name":"Gardner","surname":"Greep","email":"ggreep2a@netscape.com","description":"Sodium Citrate Blood-Pack Units, (PL 146 Plastic)","tags":"Ferula","subjects":"Diverse"},
{"id":84,"first_name":"Uta","surname":"Karchowski","email":"ukarchowski2b@addtoany.com","description":"PredniSONE","tags":"Florida Alicia","subjects":"grid-enabled"},
{"id":85,"first_name":"Peyton","surname":"Kirkham","email":"pkirkham2c@123-reg.co.uk","description":"No7 Beautifully Matte Foundation Sunscreen Broad Spectrum SPF 15 Wheat","tags":"Climbing Tribisee","subjects":"bi-directional"},
{"id":86,"first_name":"Bale","surname":"Headan","email":"bheadan2d@over-blog.com","description":"UV LOCK FLOWER WATER GEL SUN","tags":"Divaricate Phacelia","subjects":"circuit"},
{"id":87,"first_name":"Neill","surname":"Furney","email":"nfurney2e@fema.gov","description":"miconazole 1","tags":"Trailing Krameria","subjects":"parallelism"},
{"id":88,"first_name":"Romy","surname":"Moreby","email":"rmoreby2f@hc360.com","description":"Southern Medical Oxygen, Compressed","tags":"Sand Phacelia","subjects":"Phased"},
{"id":89,"first_name":"Sigfrid","surname":"Streeting","email":"sstreeting2g@timesonline.co.uk","description":"Osmitrol","tags":"Hogvine","subjects":"Face to face"},
{"id":90,"first_name":"Jayme","surname":"Topham","email":"jtopham2h@delicious.com","description":"Pomegranate Rose Hand Sanitizer","tags":"Elm","subjects":"Organic"},
{"id":91,"first_name":"Reggie","surname":"Maddison","email":"rmaddison2i@pinterest.com","description":"Anti-Itch","tags":"Jacob's-ladder","subjects":"empowering"},
{"id":92,"first_name":"Eolande","surname":"Kingcott","email":"ekingcott2j@github.com","description":"CMC Lubricant Eye Drops","tags":"Woodland Arctic Cudweed","subjects":"Triple-buffered"},
{"id":93,"first_name":"Kaia","surname":"Outram","email":"koutram2k@bloomberg.com","description":"Bermuda Grass Smut","tags":"Indian Walnut","subjects":"Synergized"},
{"id":94,"first_name":"Tammie","surname":"Cupper","email":"tcupper2l@ycombinator.com","description":"doxazosin","tags":"Hybrid Oak","subjects":"emulation"},
{"id":95,"first_name":"Eduardo","surname":"Doumer","email":"edoumer2m@hc360.com","description":"Megestrol Acetate","tags":"Flame Violet","subjects":"Streamlined"},
{"id":96,"first_name":"Irina","surname":"Carrigan","email":"icarrigan2n@slate.com","description":"Desonide","tags":"Mockernut Hickory","subjects":"extranet"},
{"id":97,"first_name":"Marcellus","surname":"Gerardin","email":"mgerardin2o@etsy.com","description":"LBEL COULEUR LUXE AMPLIFIER XP","tags":"Spreading Bladderpod","subjects":"systematic"},
{"id":98,"first_name":"Wanda","surname":"Dunican","email":"wdunican2p@ox.ac.uk","description":"Metoprolol tartrate","tags":"Miterwort","subjects":"bi-directional"},
{"id":99,"first_name":"Nev","surname":"Chazerand","email":"nchazerand2q@technorati.com","description":"Carbidopa and Levodopa","tags":"Oregon Whitetop Aster","subjects":"leading edge"},
{"id":100,"first_name":"Lemuel","surname":"Skirvin","email":"lskirvin2r@weather.com","description":"Naropin","tags":"Obtuse Buckthorn","subjects":"focus group"}]